#This is an example of API_KEYS file

CONSUMER_KEY = "twitter CONSUMER_KEY"
CONSUMER_SECRET = "twitter CONSUMER_SECRET"
ACCESS_TOKEN = "twitter ACCESS_TOKEN"
ACCESS_TOKEN_SECRET = "twitter ACCESS_TOKEN_SECRET"
BEARER_TOKEN = "twitter BEARER_TOKEN"
POSTS_TO_SKIP = "[60, 313, 420]"
L_POSTS_TO_JPEG = "[87, 874]"